// Generated by gencpp from file sailing_robot/ll.msg
// DO NOT EDIT!


#ifndef SAILING_ROBOT_MESSAGE_LL_H
#define SAILING_ROBOT_MESSAGE_LL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sailing_robot
{
template <class ContainerAllocator>
struct ll_
{
  typedef ll_<ContainerAllocator> Type;

  ll_()
    : lat(0.0)
    , lon(0.0)  {
    }
  ll_(const ContainerAllocator& _alloc)
    : lat(0.0)
    , lon(0.0)  {
  (void)_alloc;
    }



   typedef float _lat_type;
  _lat_type lat;

   typedef float _lon_type;
  _lon_type lon;





  typedef boost::shared_ptr< ::sailing_robot::ll_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sailing_robot::ll_<ContainerAllocator> const> ConstPtr;

}; // struct ll_

typedef ::sailing_robot::ll_<std::allocator<void> > ll;

typedef boost::shared_ptr< ::sailing_robot::ll > llPtr;
typedef boost::shared_ptr< ::sailing_robot::ll const> llConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sailing_robot::ll_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sailing_robot::ll_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sailing_robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'sailing_robot': ['/home/yqz/matplot_new/src/sailing_robot/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sailing_robot::ll_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sailing_robot::ll_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sailing_robot::ll_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sailing_robot::ll_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sailing_robot::ll_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sailing_robot::ll_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sailing_robot::ll_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c24029cbb90b28da08009a1a44081308";
  }

  static const char* value(const ::sailing_robot::ll_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc24029cbb90b28daULL;
  static const uint64_t static_value2 = 0x08009a1a44081308ULL;
};

template<class ContainerAllocator>
struct DataType< ::sailing_robot::ll_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sailing_robot/ll";
  }

  static const char* value(const ::sailing_robot::ll_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sailing_robot::ll_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# message for publishing position\n\
float32 lat\n\
float32 lon\n\
";
  }

  static const char* value(const ::sailing_robot::ll_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sailing_robot::ll_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lat);
      stream.next(m.lon);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ll_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sailing_robot::ll_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sailing_robot::ll_<ContainerAllocator>& v)
  {
    s << indent << "lat: ";
    Printer<float>::stream(s, indent + "  ", v.lat);
    s << indent << "lon: ";
    Printer<float>::stream(s, indent + "  ", v.lon);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SAILING_ROBOT_MESSAGE_LL_H
